### ISSUE TITLE
type of rock and minerals 

### ISSUE THREAD

**Issue by DipanwitSen** [Devanik21/ISRO_Mining_Site_FINAL_APP#23]
want to work on ml model which has types of rock and mineral so that detection will be easy .I will use convolutionary network vgg net,YOLO to work on the dataset and find the possible best way to detect rock types .This will require 2 days .
please assign me this task under hacktoctober and gssoc.

**Comment by Devanik21** [comment]
Thanks, plz explain me more, i'll be happy to know more

**Comment by Devanik21** [comment]
> want to work on ml model which has types of rock and mineral so that detection will be easy .I will use convolutionary network vgg net,YOLO to work on the dataset and find the possible best way to detect rock types .This will require 2 days . please assign me this task under hacktoctober and gssoc.

@DipanwitSen  hello, are u working on it?

**Comment by DipanwitSen** [comment]
Yes @Devanik21 I will give it today

**Comment by DipanwitSen** [comment]
> Thanks, plz explain me more, i'll be happy to know more

basically i am using yolo to capture pictures of rock and analyzing what composition it can be thereby reducing research work needed to be done on samples since from before only we are predicting
