### ISSUE TITLE
Add: "auto-label" GitHub Workflow for Automated Labeling

### ISSUE THREAD

**Issue by samyak-aditya** [Devanik21/ISRO_Mining_Site_FINAL_APP#26]
**Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

**Details:**

- This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
- By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.

Implementing this "auto-label" workflow will enhance project organization 

hey @Devanik21 Please Assign it to me with label "gssoc-ext" , "hacktoberfest-accepted" and "level2"

**Comment by Devanik21** [comment]
> **Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.
> 
> **Details:**
> 
> * This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
> * By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.
> 
> Implementing this "auto-label" workflow will enhance project organization
> 
> hey @Devanik21 Please Assign it to me with label "gssoc-ext" , "hacktoberfest-accepted" and "level2"

plz add for level1,level2 and level3 also

**Comment by Devanik21** [comment]
@samyak-aditya , are u working ?, plz edit .github/workflows/auto-label.yml
and raise a PR

**Comment by samyak-aditya** [comment]
Hey @Devanik21 yes I am Working on it

**Comment by Devanik21** [comment]
![image](https://github.com/user-attachments/assets/4a35d316-cbb6-472c-bf11-80fa4dfd549d)

**Comment by samyak-aditya** [comment]
Hey @Devanik21 I have raised the PR

**Comment by Devanik21** [comment]
@samyak-aditya ![Screenshot_2024-10-07-12-07-38-112_com.github.android-edit.jpg](https://github.com/user-attachments/assets/f3dc93f6-0117-4742-a4f2-6587858f60ce)

**Comment by samyak-aditya** [comment]
Hey @Devanik21 

![Screenshot 2024-10-07 121221](https://github.com/user-attachments/assets/a5e916ee-3a12-407f-86bd-ef76614045d3)
