### ISSUE TITLE
Add Code Of Conduct

### ISSUE THREAD

**Issue by Itachii27** [Devanik21/ISRO_Mining_Site_FINAL_APP#4]

**Comment by Itachii27** [comment]
Hi @Devanik21 Thank you for assigning this to me. Kindly add the labels **gssoc-extd**, **hacktoberfest-accepted**, **hacktoberfest** and **level-1**.

**Comment by Itachii27** [comment]
Hi @Devanik21 Please also add **hacktoberfest-accepted** label, so that I can start contributing.

**Comment by Devanik21** [comment]
> Hi @Devanik21 Thank you for assigning this to me. Kindly add the labels **gssoc-extd**, **hacktoberfest-accepted**, **hacktoberfest** and **level-1**.

done
