### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [Devanik21/ISRO_Mining_Site_FINAL_APP#5]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @Devanik21 please assign me this task with labels "gssoc-ext", "hacktoberfest-accepted" and "level1"

**Comment by Devanik21** [comment]
Hi, have you reviewed this issue.
I'm waiting for the update.

**Comment by samyak-aditya** [comment]
yes @Devanik21 I am working on this

**Comment by samyak-aditya** [comment]
Hey @Devanik21 I have raised the PR
Thanks
